# -*- coding: utf-8 -*-
"""Pos_Tagging.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jz1mrJxsFAwtzmRNLjI1PS6uQIKiMqsp
"""

!pip install spacy

import spacy

nlp = spacy.load('en_core_web_sm')

doc = nlp(u"I will google about github")

doc.text

doc[-1]

doc[2].pos_

doc[2].tag_

spacy.explain('VB')

for word in doc:
    print(word.text,"------>", word.pos_,word.tag_,spacy.explain(word.tag_))

doc2 = nlp(u"I left the room")
for word in doc2:
    print(word.text,"------>", word.pos_,word.tag_,spacy.explain(word.tag_))

doc3 = nlp(u"to the left of the room")
for word in doc3:
    print(word.text,"------>", word.pos_,word.tag_,spacy.explain(word.tag_))

